import { Inter, Nunito, Josefin_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

const inter = Nunito({ subsets: ["latin"], weight: ["700"] });
// const inter = Josefin_Sans({
//   subsets: ["latin"],
//   weight: ["600"],
// });

export const metadata = {
  title: "Micro Loop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
